In [50]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pickle

In [49]:
df = pd.read_csv("adult.csv")

In [5]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [7]:
df.shape

(48842, 15)

In [8]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [9]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [10]:
# for column in df.columns:
#   print(column, df[column].unique())

(df == "?").sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [11]:
df.replace("?", np.nan, inplace=True)

In [12]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

In [13]:
df.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [14]:
for col in ["workclass", "occupation", "native-country"]:
  df[col] = df[col].fillna(df[col].mode()[0])

In [15]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [16]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [17]:
gender_encoded = pd.get_dummies(df["gender"], prefix = "gender").astype(int)
df = pd.concat([df, gender_encoded], axis = 1)
print(df.head())

   age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married
1   38    Private   89814       HS-grad                9  Married-civ-spouse
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse
3   44    Private  160323  Some-college               10  Married-civ-spouse
4   18    Private  103497  Some-college               10       Never-married

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0
1    Farming-fishing      Husband  White    Male             0             0
2    Protective-serv      Husband  White    Male             0             0
3  Machine-op-inspct      Husband  Black    Male          7688             0
4     Prof-specialty    Own-child  White  Female             0             0

   hours-per-week native-country income  gender_Female  gender_Male
0              40  United-States  <=50K              0            1
1              50  United-States  <=50K              0            1
2              40  United-States   >50K              0            1
3              40  United-States   >50K              0            1
4              30  United-States  <=50K              1            0

In [18]:
df.drop("gender", axis = 1, inplace = True)

In [19]:
occupation_encoded = pd.get_dummies(df["occupation"], prefix = "occupation").astype(int)
df = pd.concat([df, occupation_encoded], axis =1)
print(occupation_encoded.head())

   occupation_Adm-clerical  occupation_Armed-Forces  occupation_Craft-repair  \
0                        0                        0                        0
1                        0                        0                        0
2                        0                        0                        0
3                        0                        0                        0
4                        0                        0                        0

   occupation_Exec-managerial  occupation_Farming-fishing  \
0                           0                           0
1                           0                           1
2                           0                           0
3                           0                           0
4                           0                           0

   occupation_Handlers-cleaners  occupation_Machine-op-inspct  \
0                             0                             1
1                             0                             0
2                             0                             0
3                             0                             1
4                             0                             0

   occupation_Other-service  occupation_Priv-house-serv  \
0                         0                           0
1                         0                           0
2                         0                           0
3                         0                           0
4                         0                           0

   occupation_Prof-specialty  occupation_Protective-serv  occupation_Sales  \
0                          0                           0                 0
1                          0                           0                 0
2                          0                           1                 0
3                          0                           0                 0
4                          1                           0                 0

   occupation_Tech-support  occupation_Transport-moving
0                        0                            0
1                        0                            0
2                        0                            0
3                        0                            0
4                        0                            0

In [20]:
df.drop("occupation", axis = 1, inplace = True)

In [21]:
df.isnull().sum()

age                             0
workclass                       0
fnlwgt                          0
education                       0
educational-num                 0
marital-status                  0
relationship                    0
race                            0
capital-gain                    0
capital-loss                    0
hours-per-week                  0
native-country                  0
income                          0
gender_Female                   0
gender_Male                     0
occupation_Adm-clerical         0
occupation_Armed-Forces         0
occupation_Craft-repair         0
occupation_Exec-managerial      0
occupation_Farming-fishing      0
occupation_Handlers-cleaners    0
occupation_Machine-op-inspct    0
occupation_Other-service        0
occupation_Priv-house-serv      0
occupation_Prof-specialty       0
occupation_Protective-serv      0
occupation_Sales                0
occupation_Tech-support         0
occupation_Transport-moving     0
dtype: int64

In [22]:
df["income"] = df["income"].map({
    "<=50K": 0,
    ">50K": 1
})

In [23]:
print(df)

       age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7
1       38       Private   89814       HS-grad                9
2       28     Local-gov  336951    Assoc-acdm               12
3       44       Private  160323  Some-college               10
4       18       Private  103497  Some-college               10
...    ...           ...     ...           ...              ...
48837   27       Private  257302    Assoc-acdm               12
48838   40       Private  154374       HS-grad                9
48839   58       Private  151910       HS-grad                9
48840   22       Private  201490       HS-grad                9
48841   52  Self-emp-inc  287927       HS-grad                9

           marital-status relationship   race  capital-gain  capital-loss  \
0           Never-married    Own-child  Black             0             0
1      Married-civ-spouse      Husband  White             0             0
2      Married-civ-spouse      Husband  White             0             0
3      Married-civ-spouse      Husband  Black          7688             0
4           Never-married    Own-child  White             0             0
...                   ...          ...    ...           ...           ...
48837  Married-civ-spouse         Wife  White             0             0
48838  Married-civ-spouse      Husband  White             0             0
48839             Widowed    Unmarried  White             0             0
48840       Never-married    Own-child  White             0             0
48841  Married-civ-spouse         Wife  White         15024             0

       ...  occupation_Farming-fishing occupation_Handlers-cleaners  \
0      ...                           0                            0
1      ...                           1                            0
2      ...                           0                            0
3      ...                           0                            0
4      ...                           0                            0
...    ...                         ...                          ...
48837  ...                           0                            0
48838  ...                           0                            0
48839  ...                           0                            0
48840  ...                           0                            0
48841  ...                           0                            0

       occupation_Machine-op-inspct  occupation_Other-service  \
0                                 1                         0
1                                 0                         0
2                                 0                         0
3                                 1                         0
4                                 0                         0
...                             ...                       ...
48837                             0                         0
48838                             1                         0
48839                             0                         0
48840                             0                         0
48841                             0                         0

       occupation_Priv-house-serv  occupation_Prof-specialty  \
0                               0                          0
1                               0                          0
2                               0                          0
3                               0                          0
4                               0                          1
...                           ...                        ...
48837                           0                          0
48838                           0                          0
48839                           0                          0
48840                           0                          0
48841                           0                          0

       occupation_Protective-serv  occupation_Sales  occupation_Tech-support  \
0                               0                 0                        0
1                               0                 0                        0
2                               1                 0                        0
3                               0                 0                        0
4                               0                 0                        0
...                           ...               ...                      ...
48837                           0                 0                        1
48838                           0                 0                        0
48839                           0                 0                        0
48840                           0                 0                        0
48841                           0                 0                        0

       occupation_Transport-moving
0                                0
1                                0
2                                0
3                                0
4                                0
...                            ...
48837                            0
48838                            0
48839                            0
48840                            0
48841                            0

[48842 rows x 29 columns]

In [24]:
df.dtypes

age                              int64
workclass                       object
fnlwgt                           int64
education                       object
educational-num                  int64
marital-status                  object
relationship                    object
race                            object
capital-gain                     int64
capital-loss                     int64
hours-per-week                   int64
native-country                  object
income                           int64
gender_Female                    int64
gender_Male                      int64
occupation_Adm-clerical          int64
occupation_Armed-Forces          int64
occupation_Craft-repair          int64
occupation_Exec-managerial       int64
occupation_Farming-fishing       int64
occupation_Handlers-cleaners     int64
occupation_Machine-op-inspct     int64
occupation_Other-service         int64
occupation_Priv-house-serv       int64
occupation_Prof-specialty        int64
occupation_Protective-serv       int64
occupation_Sales                 int64
occupation_Tech-support          int64
occupation_Transport-moving      int64
dtype: object

In [25]:
df.drop("fnlwgt", axis = 1, inplace = True)

In [26]:
df.drop("education", axis = 1, inplace = True)

In [27]:
marital_status_encoded = pd.get_dummies(df["marital-status"], prefix = "marital_status").astype(int)
df = pd.concat([df, marital_status_encoded], axis = 1)
marital_status_encoded.head()

,marital_status_Divorced,marital_status_Married-AF-spouse,marital_status_Married-civ-spouse,marital_status_Married-spouse-absent,marital_status_Never-married,marital_status_Separated,marital_status_Widowed
0,0,0,0,0,1,0,0
1,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0

In [28]:
relationship_encoded = pd.get_dummies(df["relationship"], prefix = "relp-status").astype(int)
df = pd.concat([df, relationship_encoded], axis = 1)
relationship_encoded.head()

,relp-status_Husband,relp-status_Not-in-family,relp-status_Other-relative,relp-status_Own-child,relp-status_Unmarried,relp-status_Wife
0,0,0,0,1,0,0
1,1,0,0,0,0,0
2,1,0,0,0,0,0
3,1,0,0,0,0,0
4,0,0,0,1,0,0

In [29]:
race_encoded = pd.get_dummies(df["race"], prefix = "race").astype(int)
df = pd.concat([df, race_encoded], axis = 1)
print(race_encoded.head())

   race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  race_Black  race_Other  \
0                        0                        0           1           0
1                        0                        0           0           0
2                        0                        0           0           0
3                        0                        0           1           0
4                        0                        0           0           0

   race_White
0           0
1           1
2           1
3           0
4           1

In [30]:
country_encoded = pd.get_dummies(df["native-country"], prefix = "country").astype(int)
df = pd.concat([df, country_encoded], axis =1)
print(country_encoded.head())

   country_Cambodia  country_Canada  country_China  country_Columbia  \
0                 0               0              0                 0
1                 0               0              0                 0
2                 0               0              0                 0
3                 0               0              0                 0
4                 0               0              0                 0

   country_Cuba  country_Dominican-Republic  country_Ecuador  \
0             0                           0                0
1             0                           0                0
2             0                           0                0
3             0                           0                0
4             0                           0                0

   country_El-Salvador  country_England  country_France  ...  \
0                    0                0               0  ...
1                    0                0               0  ...
2                    0                0               0  ...
3                    0                0               0  ...
4                    0                0               0  ...

   country_Portugal  country_Puerto-Rico  country_Scotland  country_South  \
0                 0                    0                 0              0
1                 0                    0                 0              0
2                 0                    0                 0              0
3                 0                    0                 0              0
4                 0                    0                 0              0

   country_Taiwan  country_Thailand  country_Trinadad&Tobago  \
0               0                 0                        0
1               0                 0                        0
2               0                 0                        0
3               0                 0                        0
4               0                 0                        0

   country_United-States  country_Vietnam  country_Yugoslavia
0                      1                0                   0
1                      1                0                   0
2                      1                0                   0
3                      1                0                   0
4                      1                0                   0

[5 rows x 41 columns]

In [31]:
df.drop("marital-status",axis =1, inplace = True)

In [32]:
df.drop("native-country", axis =1, inplace = True)

In [33]:
df.drop("race", axis =1, inplace = True)

In [34]:
df.drop("relationship", axis =1, inplace = True)

In [35]:
workclass_encoded = pd.get_dummies(df["workclass"], prefix = "workclass").astype(int)
df = pd.concat([df, workclass_encoded], axis = 1)
print(workclass_encoded.head())

   workclass_Federal-gov  workclass_Local-gov  workclass_Never-worked  \
0                      0                    0                       0
1                      0                    0                       0
2                      0                    1                       0
3                      0                    0                       0
4                      0                    0                       0

   workclass_Private  workclass_Self-emp-inc  workclass_Self-emp-not-inc  \
0                  1                       0                           0
1                  1                       0                           0
2                  0                       0                           0
3                  1                       0                           0
4                  1                       0                           0

   workclass_State-gov  workclass_Without-pay
0                    0                      0
1                    0                      0
2                    0                      0
3                    0                      0
4                    0                      0

In [36]:
df.drop("workclass", axis =1, inplace = True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 89 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   age                                   48842 non-null  int64
 1   educational-num                       48842 non-null  int64
 2   capital-gain                          48842 non-null  int64
 3   capital-loss                          48842 non-null  int64
 4   hours-per-week                        48842 non-null  int64
 5   income                                48842 non-null  int64
 6   gender_Female                         48842 non-null  int64
 7   gender_Male                           48842 non-null  int64
 8   occupation_Adm-clerical               48842 non-null  int64
 9   occupation_Armed-Forces               48842 non-null  int64
 10  occupation_Craft-repair               48842 non-null  int64
 11  occupation_Exec-managerial            48842 non-null  int64
 12  occupation_Farming-fishing            48842 non-null  int64
 13  occupation_Handlers-cleaners          48842 non-null  int64
 14  occupation_Machine-op-inspct          48842 non-null  int64
 15  occupation_Other-service              48842 non-null  int64
 16  occupation_Priv-house-serv            48842 non-null  int64
 17  occupation_Prof-specialty             48842 non-null  int64
 18  occupation_Protective-serv            48842 non-null  int64
 19  occupation_Sales                      48842 non-null  int64
 20  occupation_Tech-support               48842 non-null  int64
 21  occupation_Transport-moving           48842 non-null  int64
 22  marital_status_Divorced               48842 non-null  int64
 23  marital_status_Married-AF-spouse      48842 non-null  int64
 24  marital_status_Married-civ-spouse     48842 non-null  int64
 25  marital_status_Married-spouse-absent  48842 non-null  int64
 26  marital_status_Never-married          48842 non-null  int64
 27  marital_status_Separated              48842 non-null  int64
 28  marital_status_Widowed                48842 non-null  int64
 29  relp-status_Husband                   48842 non-null  int64
 30  relp-status_Not-in-family             48842 non-null  int64
 31  relp-status_Other-relative            48842 non-null  int64
 32  relp-status_Own-child                 48842 non-null  int64
 33  relp-status_Unmarried                 48842 non-null  int64
 34  relp-status_Wife                      48842 non-null  int64
 35  race_Amer-Indian-Eskimo               48842 non-null  int64
 36  race_Asian-Pac-Islander               48842 non-null  int64
 37  race_Black                            48842 non-null  int64
 38  race_Other                            48842 non-null  int64
 39  race_White                            48842 non-null  int64
 40  country_Cambodia                      48842 non-null  int64
 41  country_Canada                        48842 non-null  int64
 42  country_China                         48842 non-null  int64
 43  country_Columbia                      48842 non-null  int64
 44  country_Cuba                          48842 non-null  int64
 45  country_Dominican-Republic            48842 non-null  int64
 46  country_Ecuador                       48842 non-null  int64
 47  country_El-Salvador                   48842 non-null  int64
 48  country_England                       48842 non-null  int64
 49  country_France                        48842 non-null  int64
 50  country_Germany                       48842 non-null  int64
 51  country_Greece                        48842 non-null  int64
 52  country_Guatemala                     48842 non-null  int64
 53  country_Haiti                         48842 non-null  int64
 54  country_Holand-Netherlands            48842 non-null  int64
 55  country_Honduras                      48842 non-null  int64
 56  country_Hong                          48842 non-null  int64
 57  country_Hungary                       48842 non-null  int64
 58  country_India                         48842 non-null  int64
 59  country_Iran                          48842 non-null  int64
 60  country_Ireland                       48842 non-null  int64
 61  country_Italy                         48842 non-null  int64
 62  country_Jamaica                       48842 non-null  int64
 63  country_Japan                         48842 non-null  int64
 64  country_Laos                          48842 non-null  int64
 65  country_Mexico                        48842 non-null  int64
 66  country_Nicaragua                     48842 non-null  int64
 67  country_Outlying-US(Guam-USVI-etc)    48842 non-null  int64
 68  country_Peru                          48842 non-null  int64
 69  country_Philippines                   48842 non-null  int64
 70  country_Poland                        48842 non-null  int64
 71  country_Portugal                      48842 non-null  int64
 72  country_Puerto-Rico                   48842 non-null  int64
 73  country_Scotland                      48842 non-null  int64
 74  country_South                         48842 non-null  int64
 75  country_Taiwan                        48842 non-null  int64
 76  country_Thailand                      48842 non-null  int64
 77  country_Trinadad&Tobago               48842 non-null  int64
 78  country_United-States                 48842 non-null  int64
 79  country_Vietnam                       48842 non-null  int64
 80  country_Yugoslavia                    48842 non-null  int64
 81  workclass_Federal-gov                 48842 non-null  int64
 82  workclass_Local-gov                   48842 non-null  int64
 83  workclass_Never-worked                48842 non-null  int64
 84  workclass_Private                     48842 non-null  int64
 85  workclass_Self-emp-inc                48842 non-null  int64
 86  workclass_Self-emp-not-inc            48842 non-null  int64
 87  workclass_State-gov                   48842 non-null  int64
 88  workclass_Without-pay                 48842 non-null  int64
dtypes: int64(89)
memory usage: 33.2 MB

In [38]:
y = df["income"]

In [39]:
X = df.drop("income", axis = 1)

In [40]:
model = RandomForestClassifier(n_estimators=100, random_state = 42)
df.shape

(48842, 89)

In [41]:
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [42]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(39073, 88)
(9769, 88)
(39073,)
(9769,)

In [43]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [44]:
prediction = model.predict(X_test)

In [45]:
accuracy = accuracy_score(y_test, prediction)
print(accuracy)

0.8559729757395844

In [46]:
cm = confusion_matrix(y_test, prediction)
print(cm)

[[6874  605]
 [ 802 1488]]

In [47]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.90      0.92      0.91      7479
           1       0.71      0.65      0.68      2290

    accuracy                           0.86      9769
   macro avg       0.80      0.78      0.79      9769
weighted avg       0.85      0.86      0.85      9769

In [51]:
with open("model.pkl", "wb") as file:
  pickle.dump(model, file)

print("Model saved successfully")

Model saved successfully

In [52]:
with open("columns.pkl", "wb") as file:
  pickle.dump(X.columns.tolist(), file)

print("Columns saved successfully")

Columns saved successfully